Repository adopted-ember-addons/ember-keyboard, pull requests merged in 2020-10, with the labels that each got.

#271 Update README to add logo and adjust order
  README.md
Labels: documentation

#285 Update ember/ember-cli
  .eslintrc.js
  .travis.yml
  README.md
  addon/initializers/ember-keyboard-first-responder-inputs.js
  addon/services/keyboard.js
  addon/utils/handle-key-event.js
  config/ember-try.js
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/router.js
  tests/dummy/config/ember-cli-update.json
  tests/test-helper.js
  yarn.lock
Labels: internal

#281 support binding to "+" key
  addon/utils/keyboard-listener.js
  tests/unit/utils/is-key-test.js
Labels: enhancement
