Repository adopted-ember-addons/ember-keyboard, pull requests merged in 2022-04, with the labels that each got.

#615 move `.md` files to published package
  CHANGELOG.md
  LICENSE.md
  README.md
  addon/CHANGELOG.md
  addon/LICENSE.md
  addon/README.md
Labels: documentation

#616 replace highlight.js EOL warning in changelog by title
  addon/CHANGELOG.md
Labels: internal

#617 Prepare for ember-modifier v4
  .github/workflows/ci.yml
  addon/package.json
  addon/src/modifiers/on-key.js
  package.json
  test-app/config/ember-try.js
  yarn.lock
Labels: enhancement

#620 Fix ember-modifier v3.2 compatibility
  addon/src/modifiers/on-key.js
  test-app/config/ember-try.js
  test-app/package.json
  yarn.lock
Labels: bug

#622 Improve contributing docs
  CONTRIBUTING.md
  docs/ember-cli-build.js
  test-app/ember-cli-build.js
Labels: documentation

#626 Fix `isKey` import in documentation usage
  docs/app/templates/usage.hbs
Labels: documentation

#627 Widen `ember-modifier` dependency requirement
  .github/workflows/ci.yml
  addon/package.json
  test-app/config/ember-try.js
  test-app/package.json
  yarn.lock
Labels: enhancement

#625 auto-publish unstable packages to NPM
  .github/workflows/publish-unstable.yml
  RELEASE.md
Labels: enhancement
