Repository adopted-ember-addons/ember-keyboard, pull requests merged in 2023-06, with the labels that each got.

#730 Add @ember/string dependency to test-app
  test-app/package.json
  yarn.lock
Labels: dependencies

#732 Allow @ember/test-helpers v3 in peer dependencies
  addon/package.json
Labels: enhancement

#735 Remove test dependency ember-export-application-global that break most ember 5 tests
  test-app/package.json
Labels: dependencies

#739 Remove engines from addon package.json
  .github/workflows/ci.yml
  .github/workflows/publish-unstable.yml
  README.md
  addon/package.json
  package.json
Labels: enhancement

#736 Fix fastboot test on ember 5
  test-app/package.json
  yarn.lock
Labels: internal

#740 add ember v4 LTS to CI
  .github/workflows/ci.yml
  addon/package.json
  test-app/config/ember-try.js
Labels: internal
