Repository adopted-ember-addons/ember-keyboard, pull requests merged in 2024-08, with the labels that each got.

#780 Widen peer range for peer, @ember/test-helpers
  addon/package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#783 Skip cleanup in ember-try
  .github/workflows/ci.yml
Labels: internal

#784 Upgrade to pnpm 9
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/push-dist.yml
  package.json
  pnpm-lock.yaml
  test-app/tests/acceptance/on-key-helper-test.js
Labels: internal

#757 Don't evaluate getters when looking for handlers
  addon/src/decorators/key-responder.js
  test-app/app/components/decorator-example3/component.js
Labels: bug

#785 Use the in-repo copy of ember-keyboard using the workspace protocol
  pnpm-lock.yaml
  test-app/package.json
Labels: internal
