Repository adopted-ember-addons/ember-keyboard, pull requests merged in 2024-03, with the labels that each got.

#770 Drops support for ember < 3.28
  .github/workflows/ci.yml
  addon/package.json
  test-app/config/ember-try.js
Labels: breaking

#755 Feature: Plus sign support
  addon/src/utils/keyboard-listener.js
  test-app/app/controllers/test-scenario/on-key-helper-examples.js
  test-app/app/templates/test-scenario/on-key-helper-examples.hbs
  test-app/tests/acceptance/on-key-helper-test.js
Labels: enhancement

#771 Setup release plan
  .github/workflows/deploy-docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#772 Migrate to pnpm
  .github/workflows/ci.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/publish-unstable.yml
  .gitignore
  CONTRIBUTING.md
  addon/.prettierignore
  docs/.eslintignore
  docs/.gitignore
  docs/.npmignore
  docs/.prettierignore
  docs/README.md
  docs/config/ember-cli-update.json
  docs/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app/.eslintignore
  test-app/.gitignore
  test-app/.npmignore
  test-app/.prettierignore
  test-app/README.md
  test-app/config/ember-cli-update.json
  test-app/config/ember-try.js
  yarn.lock
Labels: internal

#773 Migrate to pnpm part 2
  .github/workflows/deploy-docs.yml
  .github/workflows/plan-release.yml
  .github/workflows/publish-unstable.yml
  .github/workflows/publish.yml
  .github/workflows/push-dist.yml
Labels: internal
